name: Auto Blogger Post

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch: # manual trigger if needed

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          FB_APP_SECRET: ${{ secrets.FB_APP_SECRET }}
          FB_APP_ID: ${{ secrets.FB_APP_ID }}
          FB_USER_ACCESS_TOKEN: ${{ secrets.FB_USER_ACCESS_TOKEN }}

        run: python item.py
